# Copyright (c) 2026 Seizh7
# Licensed under the Apache License, Version 2.0
# (http://www.apache.org/licenses/LICENSE-2.0)

"""
Entry point to generate all static visualizations for the project.

Generates PNG files in data/visualizations/ covering all 6 experiments
(K-Means, DBSCAN, SOM x freq_baseline, freq_weighted):

Per experiment (6 x 4 = 24 files):
    heatmap_{algo}_{feature_type}.png   — mean investment value per cluster
    sizes_{algo}_{feature_type}.png     — number of politicians per cluster
    pca_{algo}_{feature_type}.png       — PCA
    tsne_{algo}_{feature_type}.png      — t-SNE

Global comparison (3 files):
    metrics_silhouette.png
    metrics_davies_bouldin.png
    metrics_calinski_harabasz.png

Confusion matrices (6 files, generated by run_evaluation.py):
    confusion_{algo}_{feature_type}.png

Prerequisites:
    Run run_evaluation.py first to produce evaluation_results.csv and the
    confusion matrix PNGs.

Usage:
    python -m capitolwatch.analysis.generate_all_plots
"""

from pathlib import Path

from capitolwatch.analysis.run_visualization import (
    OUTPUT_DIR,
    run_metrics_barplots,
    run_pca_plots,
    run_simple_plots,
    run_tsne_plots,
)


def generate_all_plots(output_dir: Path = OUTPUT_DIR) -> None:
    """
    Run all visualization steps and save every PNG to output_dir.

    Args:
        output_dir (Path): Root directory where PNG files are saved.
            Defaults to data/visualizations/.
    """
    print(f"Output directory: {output_dir}\n")

    print("1. Heatmaps and cluster-size barplots")
    run_simple_plots(output_dir)

    print("\n2. Metrics comparison barplots")
    run_metrics_barplots(output_dir)

    print("\n3. PCA scatter plots")
    run_pca_plots(output_dir)

    print("\n4. t-SNE scatter plots")
    run_tsne_plots(output_dir)

    pngs = list(output_dir.glob("*.png"))
    print(f"\n{len(pngs)} PNG files in {output_dir}/")


if __name__ == "__main__":
    generate_all_plots()
